<a href="https://colab.research.google.com/github/JongHyun070105/MachineLearning2025/blob/main/Groupby_%EC%8B%A4%EC%8A%B5_2025_03_28.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

In [3]:
# flight DataFrame 만들기
flight = pd.read_csv('./Clean_Dataset.csv',encoding='cp949')
flight

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955
...,...,...,...,...,...,...,...,...,...,...,...,...
300148,300148,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265
300149,300149,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105
300150,300150,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099
300151,300151,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585
300152,300152,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585

In [5]:
# airline 기준 그룹 생성
airline_group = flight.groupby('airline')
airline_group.groups

{'AirAsia': [2, 18, 19, 27, 48, 141, 147, 148, 157, 265, 290, 325, 435, 450, 608, 609, 623, 706, 746, 782, 783, 784, 814, 978, 993, 1085, 1088, 1133, 1210, 1248, 1261, 1284, 1323, 1341, 1343, 1461, 1466, 1483, 1526, 1583, 1685, 1693, 1694, 1695, 1696, 1697, 1698, 1699, 1700, 1701, 1728, 1759, 1760, 1761, 1762, 1866, 1911, 1912, 1913, 1914, 1915, 1916, 1917, 1947, 1972, 1974, 1976, 1977, 1991, 1992, 2083, 2127, 2128, 2129, 2130, 2131, 2132, 2133, 2134, 2135, 2167, 2194, 2196, 2264, 2265, 2292, 2305, 2350, 2351, 2352, 2353, 2354, 2355, 2397, 2422, 2423, 2443, 2444, 2465, 2484, ...], 'Air_India': [16, 17, 23, 37, 40, 41, 42, 43, 44, 49, 50, 51, 52, 53, 60, 71, 74, 75, 82, 86, 87, 96, 98, 107, 108, 110, 113, 114, 115, 117, 142, 143, 144, 145, 146, 151, 152, 162, 163, 164, 166, 168, 173, 182, 189, 191, 193, 195, 196, 197, 198, 199, 207, 211, 223, 225, 229, 236, 237, 241, 242, 243, 247, 250, 266, 267, 268, 269, 272, 280, 291, 295, 303, 309, 314, 315, 316, 319, 321, 329, 333, 343, 352, 357, 361, 362, 363, 372, 376, 379, 380, 381, 385, 387, 388, 390, 391, 392, 393, 394, ...], 'GO_FIRST': [8, 9, 10, 11, 20, 21, 22, 30, 68, 72, 101, 112, 126, 127, 128, 129, 130, 131, 149, 150, 200, 201, 208, 212, 213, 222, 232, 235, 244, 245, 257, 258, 259, 260, 270, 271, 277, 278, 281, 296, 312, 313, 317, 327, 328, 342, 366, 368, 371, 384, 389, 413, 414, 415, 416, 417, 418, 436, 437, 438, 439, 440, 441, 442, 455, 465, 469, 490, 491, 496, 497, 535, 552, 586, 587, 588, 589, 590, 591, 610, 611, 612, 613, 614, 615, 616, 617, 627, 639, 640, 646, 668, 669, 672, 673, 675, 691, 762, 763, 764, ...], 'Indigo': [12, 13, 14, 15, 24, 26, 29, 31, 54, 55, 56, 57, 58, 67, 79, 81, 132, 133, 134, 135, 136, 137, 139, 140, 158, 159, 167, 170, 171, 172, 174, 175, 180, 181, 190, 224, 226, 228, 261, 262, 263, 264, 282, 283, 284, 285, 286, 287, 292, 297, 301, 302, 307, 308, 310, 323, 324, 332, 337, 348, 353, 354, 358, 359, 360, 419, 420, 421, 422, 424, 425, 426, 427, 428, 445, 446, 447, 451, 454, 456, 457, 458, 459, 466, 479, 488, 489, 522, 524, 592, 593, 594, 595, 596, 597, 598, 599, 600, 601, 625, ...], 'SpiceJet': [0, 1, 28, 38, 39, 45, 80, 118, 119, 138, 160, 161, 194, 227, 251, 252, 253, 274, 275, 294, 306, 311, 331, 398, 399, 400, 401, 402, 403, 423, 444, 448, 449, 452, 520, 540, 563, 564, 565, 566, 567, 568, 569, 570, 619, 620, 621, 622, 624, 665, 738, 739, 740, 741, 742, 743, 744, 745, 799, 800, 802, 844, 877, 898, 919, 920, 921, 922, 923, 924, 925, 971, 974, 975, 1049, 1092, 1104, 1105, 1106, 1107, 1108, 1109, 1110, 1111, 1150, 1155, 1200, 1243, 1281, 1286, 1287, 1288, 1289, 1290, 1291, 1331, 1332, 1368, 1369, 1412, ...], 'Vistara': [3, 4, 5, 6, 7, 25, 32, 33, 34, 35, 36, 46, 47, 59, 61, 62, 63, 64, 65, 66, 69, 70, 73, 76, 77, 78, 83, 84, 85, 88, 89, 90, 91, 92, 93, 94, 95, 97, 99, 100, 102, 103, 104, 105, 106, 109, 111, 116, 120, 121, 122, 123, 124, 125, 153, 154, 155, 156, 165, 169, 176, 177, 178, 179, 183, 184, 185, 186, 187, 188, 192, 202, 203, 204, 205, 206, 209, 210, 214, 215, 216, 217, 218, 219, 220, 221, 230, 231, 233, 234, 238, 239, 240, 246, 248, 249, 254, 255, 256, 273, ...]}

In [6]:
airline_group.count()

,Unnamed: 0,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
airline,,,,,,,,,,,
AirAsia,16098,16098,16098,16098,16098,16098,16098,16098,16098,16098,16098
Air_India,80892,80892,80892,80892,80892,80892,80892,80892,80892,80892,80892
GO_FIRST,23173,23173,23173,23173,23173,23173,23173,23173,23173,23173,23173
Indigo,43120,43120,43120,43120,43120,43120,43120,43120,43120,43120,43120
SpiceJet,9011,9011,9011,9011,9011,9011,9011,9011,9011,9011,9011
Vistara,127859,127859,127859,127859,127859,127859,127859,127859,127859,127859,127859

In [8]:
airline_group.mean(numeric_only=True)

              Unnamed: 0   duration  days_left         price
airline
AirAsia     95102.971922   8.941714  27.735184   4091.072742
Air_India  162945.107007  15.504235  25.497466  23507.019112
GO_FIRST    87630.797005   8.755380  27.430415   5652.007595
Indigo     110102.972658   5.795197  26.264309   5324.216303
SpiceJet    91878.408834  12.579767  24.122850   6179.278881
Vistara    177755.288310  13.326634  25.894532  30396.536302

In [11]:
flight_num = flight.select_dtypes(include='number')
flight_num.groupby(flight['airline']).mean()

              Unnamed: 0   duration  days_left         price
airline
AirAsia     95102.971922   8.941714  27.735184   4091.072742
Air_India  162945.107007  15.504235  25.497466  23507.019112
GO_FIRST    87630.797005   8.755380  27.430415   5652.007595
Indigo     110102.972658   5.795197  26.264309   5324.216303
SpiceJet    91878.408834  12.579767  24.122850   6179.278881
Vistara    177755.288310  13.326634  25.894532  30396.536302

In [12]:
flight.groupby(['airline','arrival_time']).mean(numeric_only=True)

                            Unnamed: 0   duration  days_left         price
airline   arrival_time
AirAsia   Afternoon       88816.983918   7.496335  26.980507   4206.467836
          Early_Morning   99485.108742   9.454591  27.088842   3632.676617
          Evening         80346.891383   8.628675  27.119117   4539.570963
          Late_Night     105201.948725   9.205835  29.071899   3828.437410
          Morning        107012.537642   9.934108  27.857339   3846.900653
          Night           88657.478861   8.740391  27.487202   4320.171700
Air_India Afternoon      162295.572046  15.954563  25.827142  23426.571700
          Early_Morning  138717.490455  17.037971  27.539501  18805.551542
          Evening        166211.387508  15.878056  24.942981  24459.593397
          Late_Night     166665.450239  13.214077  24.301435  28014.163158
          Morning        162496.968910  16.411557  25.655767  22792.180401
          Night          164175.090257  14.230348  25.451735  23683.386323
GO_FIRST  Afternoon       90534.220872   7.510892  27.706789   5511.206937
          Early_Morning   85682.954898  10.148961  27.533457   5537.433272
          Evening         86610.596935   8.284801  27.474795   6022.345547
          Late_Night      90382.433765   7.957369  29.245500   5306.723182
          Morning         84289.646143   9.633676  26.265846   5281.059399
          Night           87864.810293   9.087003  26.971360   5808.054728
Indigo    Afternoon      106570.254921   5.483550  26.018053   5458.553278
          Early_Morning  116218.737879   5.913914  29.270398   4107.122586
          Evening        113633.002071   6.255353  25.200587   5914.292555
          Late_Night     110790.778003   5.652350  27.798553   4989.383792
          Morning         93504.652953   4.389309  26.835436   4558.313037
          Night          114668.999528   6.176535  26.114164   5371.779781
SpiceJet  Afternoon       96337.994076  14.371315  25.279621   7116.303318
          Early_Morning   86212.106796  13.395576  20.773925   5348.022191
          Evening         97825.642908  13.826714  24.349964   7465.200285
          Late_Night     125755.550439   7.612829  23.339912   5911.436404
          Morning         88454.211881  12.866352  24.699010   5777.899010
          Night           87037.019268  11.825869  24.129980   5898.403658
Vistara   Afternoon      176534.776824  12.114402  25.469405  27905.873134
          Early_Morning  178997.086816  15.122223  26.597803  28597.738475
          Evening        178147.125191  13.679788  25.935980  31225.269687
          Late_Night     195942.545350  10.051710  26.937031  29699.180243
          Morning        177197.110088  14.913937  25.788161  30180.664694
          Night          177240.740619  12.191358  25.939596  30773.372570

In [28]:
b = flight.select_dtypes(include='number')
b.groupby([flight['airline'],flight['arrival_time']]).mean()

                            Unnamed: 0   duration  days_left         price
airline   arrival_time
AirAsia   Afternoon       88816.983918   7.496335  26.980507   4206.467836
          Early_Morning   99485.108742   9.454591  27.088842   3632.676617
          Evening         80346.891383   8.628675  27.119117   4539.570963
          Late_Night     105201.948725   9.205835  29.071899   3828.437410
          Morning        107012.537642   9.934108  27.857339   3846.900653
          Night           88657.478861   8.740391  27.487202   4320.171700
Air_India Afternoon      162295.572046  15.954563  25.827142  23426.571700
          Early_Morning  138717.490455  17.037971  27.539501  18805.551542
          Evening        166211.387508  15.878056  24.942981  24459.593397
          Late_Night     166665.450239  13.214077  24.301435  28014.163158
          Morning        162496.968910  16.411557  25.655767  22792.180401
          Night          164175.090257  14.230348  25.451735  23683.386323
GO_FIRST  Afternoon       90534.220872   7.510892  27.706789   5511.206937
          Early_Morning   85682.954898  10.148961  27.533457   5537.433272
          Evening         86610.596935   8.284801  27.474795   6022.345547
          Late_Night      90382.433765   7.957369  29.245500   5306.723182
          Morning         84289.646143   9.633676  26.265846   5281.059399
          Night           87864.810293   9.087003  26.971360   5808.054728
Indigo    Afternoon      106570.254921   5.483550  26.018053   5458.553278
          Early_Morning  116218.737879   5.913914  29.270398   4107.122586
          Evening        113633.002071   6.255353  25.200587   5914.292555
          Late_Night     110790.778003   5.652350  27.798553   4989.383792
          Morning         93504.652953   4.389309  26.835436   4558.313037
          Night          114668.999528   6.176535  26.114164   5371.779781
SpiceJet  Afternoon       96337.994076  14.371315  25.279621   7116.303318
          Early_Morning   86212.106796  13.395576  20.773925   5348.022191
          Evening         97825.642908  13.826714  24.349964   7465.200285
          Late_Night     125755.550439   7.612829  23.339912   5911.436404
          Morning         88454.211881  12.866352  24.699010   5777.899010
          Night           87037.019268  11.825869  24.129980   5898.403658
Vistara   Afternoon      176534.776824  12.114402  25.469405  27905.873134
          Early_Morning  178997.086816  15.122223  26.597803  28597.738475
          Evening        178147.125191  13.679788  25.935980  31225.269687
          Late_Night     195942.545350  10.051710  26.937031  29699.180243
          Morning        177197.110088  14.913937  25.788161  30180.664694
          Night          177240.740619  12.191358  25.939596  30773.372570

In [32]:
# 그룹화를 한 후엔 원하는 데이터만 가져오기
 # AirAsia 항공사의 Evening 시간대에 도착 데이터의 평균값만 필터링

flight.groupby(['airline','arrival_time']).mean(numeric_only=True).loc[[('AirAsia','Evening')]]

                        Unnamed: 0  duration  days_left        price
airline arrival_time
AirAsia Evening       80346.891383  8.628675  27.119117  4539.570963

In [33]:
grouped = flight.groupby(['airline','arrival_time']).mean(numeric_only=True)
grouped.loc[[('AirAsia','Evening')]]

                        Unnamed: 0  duration  days_left        price
airline arrival_time
AirAsia Evening       80346.891383  8.628675  27.119117  4539.570963