<a href="https://colab.research.google.com/github/JongHyun070105/MachineLearning2025/blob/main/Pandas_%EA%B8%B0%EC%B4%88_2025_03_21.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
data = {
    '이름' : ['차은우', '배수지', '이세영', '이도현', '김유정', '서강준', '한소희', '남주혁'],
    '학교' : ['세명고', '한국고', '세명고', '한국고', '은진고', '은진고', '한국고', '세명고'],
    '국어' : [90, 40, 80, 40, 15, 80, 55, 100],
    '영어' : [85, 35, 75, 60, 20, 100, 65, 85],
    '수학' : [100, 50, 70, 70, 10, 95, 45, 90],
    '과학' : [95, 55, 80, 75, 35, 85, 40, 95],
    '사회' : [85, 25, 75, 80, 10, 80, 35, 95],
    '주소' : ['은평구','은평구','서대문구','강서구','서대문구','강서구','은평구','고양시']
}
data

df = pd.DataFrame(data, index = ['1번','2번','3번','4번','5번','6번','7번','8번'])
df.index.name = "학번"
df

     이름   학교   국어   영어   수학  과학  사회    주소
학번
1번  차은우  세명고   90   85  100  95  85   은평구
2번  배수지  한국고   40   35   50  55  25   은평구
3번  이세영  세명고   80   75   70  80  75  서대문구
4번  이도현  한국고   40   60   70  75  80   강서구
5번  김유정  은진고   15   20   10  35  10  서대문구
6번  서강준  은진고   80  100   95  85  80   강서구
7번  한소희  한국고   55   65   45  40  35   은평구
8번  남주혁  세명고  100   85   90  95  95   고양시

In [4]:
df.to_excel('score.xlsx')

In [5]:
df.describe()

               국어          영어          수학         과학         사회
count    8.000000    8.000000    8.000000   8.000000   8.000000
mean    62.500000   65.625000   66.250000  70.000000  60.625000
std     29.519969   26.917533   30.325614  23.754699  32.120032
min     15.000000   20.000000   10.000000  35.000000  10.000000
25%     40.000000   53.750000   48.750000  51.250000  32.500000
50%     67.500000   70.000000   70.000000  77.500000  77.500000
75%     82.500000   85.000000   91.250000  87.500000  81.250000
max    100.000000  100.000000  100.000000  95.000000  95.000000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8 entries, 1번 to 8번
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      8 non-null      object
 1   학교      8 non-null      object
 2   국어      8 non-null      int64
 3   영어      8 non-null      int64
 4   수학      8 non-null      int64
 5   과학      8 non-null      int64
 6   사회      8 non-null      int64
 7   주소      8 non-null      object
dtypes: int64(5), object(3)
memory usage: 576.0+ bytes

In [7]:
df.head()

     이름   학교  국어  영어   수학  과학  사회    주소
학번
1번  차은우  세명고  90  85  100  95  85   은평구
2번  배수지  한국고  40  35   50  55  25   은평구
3번  이세영  세명고  80  75   70  80  75  서대문구
4번  이도현  한국고  40  60   70  75  80   강서구
5번  김유정  은진고  15  20   10  35  10  서대문구

In [8]:
df.tail(3)

     이름   학교   국어   영어  수학  과학  사회   주소
학번
6번  서강준  은진고   80  100  95  85  80  강서구
7번  한소희  한국고   55   65  45  40  35  은평구
8번  남주혁  세명고  100   85  90  95  95  고양시

In [9]:
df.values

array([['차은우', '세명고', 90, 85, 100, 95, 85, '은평구'],
       ['배수지', '한국고', 40, 35, 50, 55, 25, '은평구'],
       ['이세영', '세명고', 80, 75, 70, 80, 75, '서대문구'],
       ['이도현', '한국고', 40, 60, 70, 75, 80, '강서구'],
       ['김유정', '은진고', 15, 20, 10, 35, 10, '서대문구'],
       ['서강준', '은진고', 80, 100, 95, 85, 80, '강서구'],
       ['한소희', '한국고', 55, 65, 45, 40, 35, '은평구'],
       ['남주혁', '세명고', 100, 85, 90, 95, 95, '고양시']], dtype=object)

In [10]:
df.index

Index(['1번', '2번', '3번', '4번', '5번', '6번', '7번', '8번'], dtype='object', name='학번')

In [11]:
df.columns

Index(['이름', '학교', '국어', '영어', '수학', '과학', '사회', '주소'], dtype='object')

In [12]:
df.shape

(8, 8)

In [13]:
df['국어'].describe()

count      8.000000
mean      62.500000
std       29.519969
min       15.000000
25%       40.000000
50%       67.500000
75%       82.500000
max      100.000000
Name: 국어, dtype: float64

In [14]:
df['국어']

학번
1번     90
2번     40
3번     80
4번     40
5번     15
6번     80
7번     55
8번    100
Name: 국어, dtype: int64

In [15]:
df['영어'].min()

20

In [16]:
df['과학'].max()

95

In [18]:
df['국어'].nlargest(5)

학번
8번    100
1번     90
3번     80
6번     80
7번     55
Name: 국어, dtype: int64

In [19]:
df['국어'].mean()

np.float64(62.5)

In [20]:
df['과학'].count()

np.int64(8)

In [21]:
df['학교'].unique()

array(['세명고', '한국고', '은진고'], dtype=object)

In [22]:
df['학교'].nunique()

3

In [23]:
df['주소'].unique()

array(['은평구', '서대문구', '강서구', '고양시'], dtype=object)

In [24]:
df['주소'].nunique()

4

In [25]:
df['주소']

학번
1번     은평구
2번     은평구
3번    서대문구
4번     강서구
5번    서대문구
6번     강서구
7번     은평구
8번     고양시
Name: 주소, dtype: object

In [26]:
df[['이름','주소']]

     이름    주소
학번
1번  차은우   은평구
2번  배수지   은평구
3번  이세영  서대문구
4번  이도현   강서구
5번  김유정  서대문구
6번  서강준   강서구
7번  한소희   은평구
8번  남주혁   고양시

In [27]:
df.columns[0]

'이름'

In [28]:
df[df.columns[0]]

학번
1번    차은우
2번    배수지
3번    이세영
4번    이도현
5번    김유정
6번    서강준
7번    한소희
8번    남주혁
Name: 이름, dtype: object

In [29]:
df[df.columns[-1]]

학번
1번     은평구
2번     은평구
3번    서대문구
4번     강서구
5번    서대문구
6번     강서구
7번     은평구
8번     고양시
Name: 주소, dtype: object

In [33]:
df['영어'][0:5]

학번
1번    85
2번    35
3번    75
4번    60
5번    20
Name: 영어, dtype: int64

In [31]:
df[['이름','주소']][:3]

     이름    주소
학번
1번  차은우   은평구
2번  배수지   은평구
3번  이세영  서대문구

In [34]:
df.loc['1번']

이름    차은우
학교    세명고
국어     90
영어     85
수학    100
과학     95
사회     85
주소    은평구
Name: 1번, dtype: object

In [38]:
df.loc[['5번','3번'], '국어']

학번
5번    15
3번    80
Name: 국어, dtype: int64

In [39]:
df.loc[['1번','3번'],['국어','영어','수학']]

    국어  영어   수학
학번
1번  90  85  100
3번  80  75   70

In [40]:
df.iloc[0]

이름    차은우
학교    세명고
국어     90
영어     85
수학    100
과학     95
사회     85
주소    은평구
Name: 1번, dtype: object

In [41]:
df.iloc[3]

이름    이도현
학교    한국고
국어     40
영어     60
수학     70
과학     75
사회     80
주소    강서구
Name: 4번, dtype: object

In [43]:
df.iloc[1:3]

     이름   학교  국어  영어  수학  과학  사회    주소
학번
2번  배수지  한국고  40  35  50  55  25   은평구
3번  이세영  세명고  80  75  70  80  75  서대문구